# Generated by Django 4.1.7 on 2023-04-20 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioasset_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_values', to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
