# Generated by Django 4.1.7 on 2023-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioasset_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
